version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # command: sleep infinity
    command: /bin/sh -c "cd /workspace/web && yarn && exec sleep infinity"
    network_mode: host
