name: Build and Deploy to GitHub Pages

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: SetUp Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "scripts/scraper/yarn.lock"

      - name: Install scraper dependencies
        working-directory: ./scripts/scraper
        run: yarn install --frozen-lockfile

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run data collection scripts
        working-directory: ./scripts/shell
        run: |
          chmod +x ./fetch.sh ./collect_all_files.sh
          ./fetch.sh
          ./collect_all_files.sh

      - name: Run scraper
        working-directory: ./scripts/scraper
        run: yarn run scrape

      - name: Run Data Processing Script
        working-directory: ./scripts/python
        run: |
          python main.py

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"

      - name: Install frontend dependencies
        working-directory: ./web
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: ./web
        env:
          NODE_ENV: production
          VITE_GA_MEASUREMENT_ID: G-TLZB1WBVE6
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment files
        run: |
          mkdir -p _site
          cp -a web/dist/. _site/
          mkdir -p _site/data
          cp -r data/output/* _site/data/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
